repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: dbt-deps
        name: dbt deps
        entry: poetry run dbt deps --project-dir transform/dbt --profiles-dir transform/dbt/profiles
        language: system
        files: ^transform/dbt/packages\.yml$
        stages: [pre-commit]
        pass_filenames: false

  - repo: local
    hooks:
      - id: dbt-lint
        name: dbt lint
        entry: poetry run dbt parse --project-dir transform/dbt --profiles-dir transform/dbt/profiles
        language: system
        files: ^transform/dbt/.*\.sql$
        stages: [pre-commit]
        pass_filenames: false

  - repo: local
    hooks:
      - id: mypy
        name: mypy (poetry)
        entry: poetry run mypy
        language: system
        types: [python]
        stages: [pre-push]

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest unit tests (poetry)
        entry: poetry run pytest -m unit --tb=short
        language: system
        types: [python]
        stages: [pre-push]
        pass_filenames: false
