# file: docker-compose.yml
services:
  worker:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - FINANCE_DIR_HOST=${FINANCE_DIR_HOST}
      - FINANCE_DATA_DIR_CONTAINER=${FINANCE_DATA_DIR_CONTAINER}
      - EXPORT_FINANCE_TABLE=${EXPORT_FINANCE_TABLE}
      - GOOGLE_SA_JSON_PATH=${GOOGLE_SA_JSON_PATH}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
      - GOOGLE_TABLE_NAME=${GOOGLE_TABLE_NAME}
      - DBT_DIR=${DBT_DIR}
      - DBT_PROFILES_DIR=${DBT_PROFILES_DIR}
      - DAGSTER_HOME_PATH=${DAGSTER_HOME_PATH}
      - DUCKDB_PATH=${DUCKDB_PATH}
    volumes:
      # Inputs: mount host data directory to container
      - type: bind
        source: ${FINANCE_DIR_HOST}
        target: ${FINANCE_DATA_DIR_CONTAINER}

      # Project code & state
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./orchestration
        target: /app/orchestration
      - type: bind
        source: ./transform
        target: /app/transform
      - type: bind
        source: ./quality
        target: /app/quality
      - type: bind
        source: ./docs
        target: /app/docs
      - type: bind
        source: ./data/warehouse
        target: /app/data/warehouse
      - type: bind
        source: ./data/dagster_home
        target: /app/dagster_home
      - type: bind
        source: ./credentials
        target: /app/credentials
        read_only: true
    command: bash -lc "dagster dev -h 0.0.0.0 -p 3000 --workspace /app/workspace.yaml"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "bash", "-lc", "python -c 'import duckdb;print(1)'"]
      interval: 15s
      timeout: 5s
      retries: 10
