# file: transform/dbt_project.yml
name: finance_analytics_pipeline
version: 1.0.0
profile: local_duckdb
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target"]

models:
  finance_analytics_pipeline:
    +materialized: table
    staging:
      +schema: stg
    core:
      +schema: core
    marts:
      +schema: mart

    integration_marts:
      +schema: imart
      +materialized: view

seeds:
  +schema: seed
  +delimiter: "\t"

on-run-start:
  - "{{ assert_env() }}"
  - "{{ assert_source('prod_raw','t_bank_transactions') }}"
