# file: transform/dbt_project.yml
name: local_duckdb_pipeline
version: 1.0.0
profile: local_duckdb
model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  local_duckdb_pipeline:
    +materialized: table
    marts:
      +schema: marts
    core:
      +schema: core
    staging:
      +schema: staging



