# file: transform/profiles.yml
local_duckdb:
  target: prod
  outputs:
    prod:
      type: duckdb
      schema: prod
      path: "{{ env_var('DUCKDB_PATH', '/app/data/warehouse/analytics.duckdb') }}"
      threads: 4
